class RetryError(Exception):
    pass


class OperationError(Exception):
    pass
